- name: Install bundler
  sudo_user: 'vagrant'
  command: bash -lc "gem install bundler"

- name: Install gems
  sudo_user: 'vagrant'
  command: bash -lc "cd ~vagrant/rails-project && bundle install" -u 'vagrant'

- name: Copy original database.yml file
  sudo_user: 'vagrant'
  command: cp ~vagrant/rails-project/config/database.yml ~vagrant/rails-project/config/database.yml.orig

- name: Add vagrant specific database.yml file
  sudo_user: 'vagrant'
  copy: src=../files/database.yml dest=~vagrant/rails-project/config/database.yml

- name: Create database
  command: bash -lc "cd ~vagrant/rails-project && RAILS_ENV=production && bundle exec rake db:create && bundle exec rake db:migrate" -u 'vagrant'
#
# - name: Precompile assets
#   command: bash -lc "cd ~vagrant/rails-project && RAILS_ENV=production rake assets:precompile" -u 'vagrant'
#   when: precompile_assets
#
- name: Start unicorn
  sudo_user: 'vagrant'
  command: bash -lc "cd ~vagrant/rails-project && bundle exec unicorn_rails -c config/unicorn.rb -D" -u 'vagrant'

- name: Restart nginx
  service: name=nginx state=restarted
