- name: Install bundler
  sudo_user: 'vagrant'
  command: bash -lc "gem install bundler"

- name: Install gems
  sudo_user: 'vagrant'
  command: bash -lc "cd ~vagrant/rails-project && bundle install" -u 'vagrant'

- name: Copy original database.yml file
  sudo_user: 'vagrant'
  command: cp ~vagrant/rails-project/config/database.yml ~vagrant/rails-project/config/database.yml.orig creates=~vagrant/rails-project/config/database.yml.orig

- name: Add vagrant specific database.yml file
  sudo_user: 'vagrant'
  copy: src=../files/database.yml dest=~vagrant/rails-project/config/database.yml

- name: Create database
  sudo_user: 'vagrant'
  command: bash -lc "cd ~vagrant/rails-project && RAILS_ENV=production bundle exec rake db:create" -u 'vagrant'

- name: Load database schema
  sudo_user: 'vagrant'
  command: bash -lc "cd ~vagrant/rails-project && RAILS_ENV=production bundle exec rake db:schema:load" -u 'vagrant'

- name: Seed database
  sudo_user: 'vagrant'
  command: bash -lc "cd ~vagrant/rails-project && RAILS_ENV=production bundle exec rake db:seed" -u 'vagrant'
  when: seed_database

- name: Precompile assets
  sudo_user: 'vagrant'
  command: bash -lc "cd ~vagrant/rails-project && RAILS_ENV=production rake assets:precompile" -u 'vagrant'
  when: precompile_assets

- name: Start unicorn
  sudo_user: 'vagrant'
  command: bash -lc "cd ~vagrant/rails-project && bundle exec unicorn_rails -c config/unicorn.rb -E production -D" -u 'vagrant'

- name: Restart nginx
  service: name=nginx state=restarted
