- name: Install ruby {{ version }}
  shell: /usr/local/rvm/bin/rvm install {{ version }} executable=/bin/bash

- name: Set default ruby to {{ version }}
  shell: /usr/local/rvm/bin/rvm alias create default {{ version }} executable=/bin/bash
