- name: Install ruby {{ version }}
  sudo_user: 'vagrant'
  command: bash -lc "rbenv install {{ version }}" -u 'vagrant'

- sudo_user: 'vagrant'
  command: bash -lc "rbenv rehash" -u vagrant

- name: Set default ruby to {{ version }}
  sudo_user: 'vagrant'
  command: bash -lc "rbenv global {{ version }}" -u 'vagrant'
