- name: Install dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
    - ruby-dev
    - git-core
    - libpq-dev
    - htop

- name: Install rbenv
  sudo_user: 'vagrant'
  git: repo=git://github.com/sstephenson/rbenv.git dest=~vagrant/.rbenv accept_hostkey=true

- name: Copy rbenv.sh to remote
  sudo_user: 'vagrant'
  copy: src=../files/rbenv.sh dest=~vagrant/.rbenv.sh owner=vagrant mode=700

- name: Source rbenv shims file
  sudo_user: 'vagrant'
  lineinfile: dest=~/.bash_profile insertafter=EOF regexp='rbenv' line="source ~/.rbenv.sh" create=yes

- name: Create plugin directory
  sudo_user: 'vagrant'
  file: path=~vagrant/.rbenv/plugins owner=vagrant group=vagrant mode=0755 state=directory

- name: Install ruby-build
  sudo_user: 'vagrant'
  git: repo=git://github.com/sstephenson/ruby-build.git dest=~vagrant/.rbenv/plugins/ruby-build accept_hostkey=true
