- name: Install dependencies
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - python-psycopg2

- name: Install postgress {{ version }}
  apt: pkg=postgresql-{{ version }} state=installed update_cache=true

- name: Change postgresql.conf
  lineinfile: dest=/etc/postgresql/{{ version }}/main/postgresql.conf insertafter=EOF regexp='#listen_addresses' line="listen_addresses = '*'" state=present

- name: Copy pg_hba.conf
  copy: src=../files/pg_hba.conf dest=/etc/postgresql/{{ version }}/main/

- name: Restart postgres
  service: name=postgresql state=restarted

- name: Create postgres user for rails app
  sudo: yes
  sudo_user: 'vagrant'
  postgresql_user: name=vagrant_rails password=rails role_attr_flags=CREATEDB,NOSUPERUSER
